#!/bin/sh

lb config noauto \
   --mode ubuntu \
   --system live \
   -b netboot \
   -d trusty \
   --initsystem sysvinit \
   --syslinux-theme live-build \
   --chroot-filesystem squashfs \
   --apt-options "-oAcquire::ForceIPv4=true -y" \
   --archive-areas "main universe multiverse restricted" \
   --linux-flavours "virtual-lts-xenial" \
   --linux-packages "linux-image linux-image-extra" \
   --initramfs live-boot \
   "${@}"


